#include "verilated.h"
extern "C" {
    #include "wrapper.h"
}
#include "Vtop.h"  // Generated by Verilator

struct VtopWrapper {
    Vtop* model;
};

extern "C" VtopWrapper* Vtop_new() {
    VtopWrapper* wrapper = new VtopWrapper();
    wrapper->model = new Vtop();
    return wrapper;
}

extern "C" void Vtop_delete(VtopWrapper* wrapper) {
    delete wrapper->model;
    delete wrapper;
}

extern "C" void Vtop_eval(VtopWrapper* wrapper) {
    wrapper->model->eval();
}

extern "C" void Vtop_push_char(VtopWrapper* wrapper, char c) {
    wrapper->model->in = c;
}
extern "C" void Vtop_push_done(VtopWrapper* wrapper) {
    wrapper->model->done = 1;
}

extern "C" char Vtop_is_valid(VtopWrapper* wrapper) {
    return wrapper->model->out;
}
extern "C" char Vtop_get_output(VtopWrapper* wrapper) {
    return wrapper->model->output__;
}
